name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: API
    env:
      sql-connstring: ${{ secrets.SQL_CONNSTRING }}
      email-api-key: ${{ secrets.EMAIL_API_KEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: osmosiseds.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t osmosiseds.azurecr.io/osmosis:${{ github.sha }}
        docker push osmosiseds.azurecr.io/osmosis:${{ github.sha }}