name: 'Release'

on: 
  push:
    branches:
      - master

jobs:
  upload_binaries:
    name: 'Build image'
    runs-on: ['azure-identity']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Declare variables
      id: vars
      shell: bash
      run: |

        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=repository::${GITHUB_REPOSITORY#*/}"
        REPO=${GITHUB_REPOSITORY#*/}
        arrREPO=(${REPO//-/ })
        if [ ${#arrREPO[@]} -eq 2 ]; then
          echo "::set-output name=customer::${arrREPO[0]}"
          echo "::set-output name=application::${arrREPO[1]}"
        else
          echo ${arrREPO}
          exit 1
        fi

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build image
      run: docker build -t osmosiseds.azurecr.io/${{ steps.vars.outputs.customer }}/${{ steps.vars.outputs.application }}:${{ steps.tag_version.outputs.new_version }}.${{ steps.vars.outputs.sha_short }} .

    - name: Azure login
      run: az login --identity

    - name: ACR login
      run: az acr login -n osmosiseds

    - name: ACR push
      run: docker push osmosiseds.azurecr.io/${{ steps.vars.outputs.customer }}/${{ steps.vars.outputs.application }}:${{ steps.tag_version.outputs.new_version }}.${{ steps.vars.outputs.sha_short }}
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}      